name = "JImages"
uuid = "6575ce61-b8f8-474f-b731-531c2c35fe24"
authors = ["jjgomezcadenas <no@mail> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
